# -*- coding: utf-8 -*-
"""MPI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rh3mePw_6ZNSgT9dnVV84Q2KpcgfLoT0
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv(r"c:\Users\Haris_hp\Downloads\ai4i+2020+predictive+maintenance+dataset\ai4i2020.csv")
print(data.head())

data.isnull().sum()

data.describe()

data.shape

data.columns

data["Machine failure"].value_counts()

numerical_columns = ['Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]','TWF', 'HDF', 'PWF', 'OSF',
       'RNF']

for col in numerical_columns :
  sns.scatterplot(x=data['Machine failure'] , y=data[col])
  plt.show()

sns.heatmap(data.corr(numeric_only=True),annot=True,cmap='RdYlGn')

for col in data.columns :
  sns.boxplot(x=data['Air temperature [K]'] , y=data[col])

data['temperature_difference'] = data['Process temperature [K]'] - data['Air temperature [K]']
data['Power'] = (data['Rotational speed [rpm]'] * data['Torque [Nm]'])  * 2 * (3.12 / 60)

# Initialize 'Failure_Risk' column to 0
data['Failure_Risk'] = 0

# Use boolean indexing with .loc and the logical OR operator to assign 1 where the condition is met
data.loc[(data['Power'] < 3500) | (data['Power'] > 9000), 'Failure_Risk'] = 1

data['Energy Loss'] = data['Rotational speed [rpm]'] * data['Tool wear [min]']

data['Overstrain_Index'] = data['Torque [Nm]'] * data['Tool wear [min]']

data['HDF_Risk'] = ((data['temperature_difference'] < 8.6) & (data['Rotational speed [rpm]'] < 1380)).astype(int)

from sklearn.preprocessing import LabelEncoder , OneHotEncoder , StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

data.columns

metafeatures = ['UDI' ,  'Product ID']

categorical_columns = ['Type']
numerical_columns = ['Air temperature [K]',
    'Process temperature [K]',
    'Rotational speed [rpm]',
    'Torque [Nm]',
    'Tool wear [min]',
    'temperature_difference',
    'Power',
    'Energy Loss',
    'Overstrain_Index']

binary_columns = ['HDF_Risk' , 'Failure_Risk']

primary_target = ['Machine failure']
sub_failure_node = ['TWF', 'HDF', 'PWF', 'OSF', 'RNF']


x = data.drop(columns=primary_target)
y = data[primary_target]
x_train , x_test , y_train , y_test  = train_test_split(x , y , test_size=0.2 , random_state=42)

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder , OneHotEncoder , StandardScaler, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report , r2_score

metafeatures_pipeline = Pipeline(steps=[
    ('ordinal_encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1))
])

categorical_pipeline = Pipeline(steps=[
    ('one_hot_encoder', OneHotEncoder(handle_unknown='ignore'))
])

numerical_pipeline = Pipeline(steps=[
    ('Standard_Scaler', StandardScaler())
])

processor = ColumnTransformer(transformers=(
    ('metafeatures' , metafeatures_pipeline , metafeatures),
    ('categorical' , categorical_pipeline , categorical_columns),
    ('numerical' , numerical_pipeline , numerical_columns),
    ('binary' , 'passthrough' , binary_columns)
))

Model_pipeline = Pipeline(steps=[
    ('processor' , processor),
    ('Xgboost', XGBClassifier())
])

Model_pipeline

model = Model_pipeline.fit(x_train , y_train.values.ravel())
model_predictions = model.predict(x_test)
model_training_prediction = model.predict(x_train)

print(r2_score(y_test.values.ravel() , model_predictions))

from sklearn.model_selection import RandomizedSearchCV

param_grid = {
    'Xgboost__n_estimators': [100, 200, 300],
    'Xgboost__max_depth': [3, 5, 7, 10], # Replaced [None, 10, 20, 30] with integer depths
    'Xgboost__learning_rate': [0.01, 0.1, 0.2],
    'Xgboost__min_child_weight': [1, 2, 4] # Analogous to min_samples_leaf
}

random_search = RandomizedSearchCV(model, param_distributions=param_grid, n_iter=10, cv=5, scoring='accuracy', verbose=2, random_state=42, n_jobs=-1)
random_search.fit(x_train, y_train.values.ravel())

print("Best Parameters:", random_search.best_params_)
print("Best Score:", random_search.best_score_)

best_model = random_search.best_estimator_
y_pred = best_model.predict(x_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

import joblib 

joblib.dump(Model_pipeline , 'Maintenance Preditive Intelligence.pkl')

